### PR TITLE
Rename README.md to Dash

### PR DESCRIPTION
**Pull request by dash4397**

### CODE REVIEW

**Comment by Rizkard** [comment]
Rizkard

**Comment by Rizkard** [comment]
Nice air project

**Comment by cantiir2** [comment]
All humans need air, let's support this project carefully

**Comment by indoairdrop7** [comment]
Ok


Pada tanggal Min, 18 Jul 2021 00.24, cantiir2 ***@***.***>
menulis:

**Comment by Tayyabchannarg** [comment]
Thanks

**Comment by indoairdrop7** [comment]
Done.

Pada tanggal Min, 18 Jul 2021 04.05, Tayyabchannarg <
***@***.***> menulis:

**Comment by indoairdrop7** [comment]
Yes this is

Pada tanggal Min, 18 Jul 2021 04.08, Airdrop Indo ***@***.***>
menulis:

**Comment by cauut** [comment]
hi

**Comment by djelidkhaled** [comment]
Hello

**Comment by Afro-stack** [comment]
Hi

**Comment by alswede0101** [comment]
hello

**Comment by alswede0101** [comment]
hi

**Pull request closed without merging**
