### PR TITLE
Create Aircashflow

### PR DESCRIPTION
**Pull request by lakenside**

### CODE REVIEW

**Comment by Josydee19** [comment]
Air coin to the moon.

A good project

**Comment by jovzpin** [comment]
oh yeah!

**Comment by andryori** [comment]
Nice move

**Comment by Seyyyp13** [comment]
let's gooo

**Comment by uchkelamoet** [comment]
an absolute great project. I'm thrilled at the stronghold of the project. Amazing to see tbvh.

**Pull request closed without merging**
