### PR TITLE
Lonewanderer

### PR DESCRIPTION
**Pull request by RareSentience**
Im new at this

### CODE REVIEW

**Review by RareSentience — COMMENTED** [review]
>   ##`

https://user-images.githubusercontent.com/87048292/126873080-64ac19da-df2c-4056-bf21-45ea14f5a1bb.mp4

**Comment by Ahmadreza2010** [comment]
Hi Tel02121

🔸3 USDT Each to 500 Random participants
👫10 USDT each to 50 top referrers

📎 Referral link: https://t.me/CoreStarter_bot?start=r02178423570

👬 Referrals: 0

Your Submitted details:
-------------------
Telegram: Tel02121
Twitter: https://twitter.com/CoreStarter/status/1418557163052617728?s=20
Medium: https://medium.com/@zamaniahmadreza25
YouTube: Zamaniahmadreza5@gmail.com
BEP-20 USDT wallet: 0x8280FEBf481C23B235e510416190e5933aFf7782

If your submitted data is wrong then you can restart the bot and resubmit the data again by clicking /start before airdrop end.

Note: Airdrop will end on 5th August, rewards will be distributed to participants BEP-20 USDT wallet within a week after airdrop ends. Participants must complete at least the mandatory tasks and submit details correctly to be eligible for the airdrop.

**Comment by Wakj258** [comment]
Best project for future

**Comment by Tuncayigit** [comment]
Good project

**Pull request closed without merging**
