### PR TITLE
Create AirCash

### PR DESCRIPTION
**Pull request by ranjeetkumar237**
The Great #AirCoin

### CODE REVIEW

**Comment by sedenk73** [comment]
good project sir

**Comment by afosco** [comment]
Strong project and promising project

**Comment by Azumonie04** [comment]
Alright thanks

**Comment by adamparol** [comment]
Follow the light, fly with the Air.

**Comment by saqibanwer** [comment]
Nice project

**Comment by wanswp** [comment]
I hope this project is a success, sir, and then it becomes one of the best cryptos, I am enthusiastic about participating in this and also supporting it.

**Pull request closed without merging**
