### PR TITLE
Create Alpin adam

### PR DESCRIPTION
**Pull request by alvin02082000**

### CODE REVIEW

**Comment by F3hofc** [comment]
To moon

**Comment by HBALH** [comment]
nice

**Comment by baux01** [comment]
great project

**Comment by Ahmed1002medo** [comment]
Nice project

**Comment by schwein364** [comment]
Alright thanks

**Comment by Alisaki1361** [comment]
This project ready to launch 🚀😎👍

**Comment by Benkben** [comment]
Interesting project

**Pull request closed without merging**
